"""Add Central American (HND, SLV, NIC) and all missing African countries."""
import json, os, math

SCENARIO_PATH = os.path.join(os.path.dirname(__file__), '..', 'backend', 'app', 'data', 'scenarios', 'default_2016.json')

def eq(s, bp, g):
    """Scale equipment from strength, budget %, GDP."""
    budget = g * bp / 100
    sc = math.sqrt(max(0.05, budget / 20))
    bases = [
        [0,30,80,200,400,650,1000,1600,2500,4000,6500],  # chars
        [0,10,30, 70,120,180, 240, 320, 420, 580, 800],  # jets
        [0, 1, 2,  3,  5,  7,  10,  13,  17,  25,  38],  # ships
        [0, 0, 0,  1,  2,  3,   5,   8,  12,  20,  35],  # subs
        [0,10,30, 60,100,150, 220, 310, 420, 580, 800],  # heli
        [0,30,100,300,550,900,1300,1900,2800,4000,6500],  # arty
    ]
    s = max(0, min(10, s))
    def sc2(b): return max(0, round(b * sc))
    return {
        'chars_combat':    sc2(bases[0][s]),
        'avions_chasse':   sc2(bases[1][s]),
        'navires_guerre':  sc2(bases[2][s]),
        'sous_marins':     sc2(bases[3][s]),
        'helicopteres':    sc2(bases[4][s]),
        'artillerie':      sc2(bases[5][s]),
    }

def sec(a, i, s): return {'agriculture': float(a), 'industrie': float(i), 'services': float(s)}
def ns(sv, fa, en, ei): return {'sovereignty': float(sv), 'food_autonomy': float(fa), 'energy_autonomy': float(en), 'economic_independence': float(ei)}

NEW = {
    # ── Amérique centrale ────────────────────────────────────────────────────
    'HND': {
        'id':'HND','name':'Honduras','flag':'🇭🇳','capital':'Tegucigalpa',
        'continent':'Amérique du Nord','population':8098000,
        'government_type':'présidentiel','ideology':'démocratie_fragile',
        'leader':'Juan Orlando Hernández',
        'alliances':[],
        'economy':{'gdp':20.4,'gdp_per_capita':2280,'gdp_growth':3.7,'inflation':3.3,
                   'unemployment':5.5,'debt_pct_gdp':46.8,'currency':'HNL',
                   'main_sectors':['agriculture','textile','exportations','café'],
                   'sectors':sec(14,27,59)},
        'military':{'strength':2,'active_personnel':12000,'nuclear_weapons':False,
                    'defense_budget_pct':1.6,'equipment':eq(2,1.6,20.4)},
        'national_stats':ns(45,65,38,32),
        'relations':{'USA':55,'MEX':40,'GTM':35,'SLV':30,'NIC':15,'CRI':35,'COL':30},
        'personality_traits':['pro_américain','économie_fragile','narco_violence','CAFTA'],
        'description':"Le Honduras est l'un des pays les plus pauvres d'Amérique latine, confronté à la violence des gangs et à la corruption, très dépendant de l'aide américaine.",
        'color':'#0073CF',
    },
    'SLV': {
        'id':'SLV','name':'El Salvador','flag':'🇸🇻','capital':'San Salvador',
        'continent':'Amérique du Nord','population':6344000,
        'government_type':'présidentiel','ideology':'semi_démocratique',
        'leader':'Salvador Sánchez Cerén',
        'alliances':[],
        'economy':{'gdp':26.8,'gdp_per_capita':4200,'gdp_growth':2.4,'inflation':0.6,
                   'unemployment':7.0,'debt_pct_gdp':67.1,'currency':'USD',
                   'main_sectors':['textile','café','transferts_migratoires','commerce'],
                   'sectors':sec(12,27,61)},
        'military':{'strength':2,'active_personnel':15000,'nuclear_weapons':False,
                    'defense_budget_pct':1.0,'equipment':eq(2,1.0,26.8)},
        'national_stats':ns(48,62,35,35),
        'relations':{'USA':55,'MEX':40,'GTM':45,'HND':30,'NIC':20,'CRI':40,'COL':30},
        'personality_traits':['pro_américain','économie_dollarisée','violence_gangs','CAFTA'],
        'description':"Le pays le plus densément peuplé d'Amérique centrale, El Salvador dollarisé souffre de la violence des gangs MS-13 et Barrio 18 malgré une économie en légère croissance.",
        'color':'#0F47AF',
    },
    'NIC': {
        'id':'NIC','name':'Nicaragua','flag':'🇳🇮','capital':'Managua',
        'continent':'Amérique du Nord','population':6218000,
        'government_type':'présidentiel_autoritaire','ideology':'socialisme_autoritaire',
        'leader':'Daniel Ortega',
        'alliances':[],
        'economy':{'gdp':13.2,'gdp_per_capita':2120,'gdp_growth':4.7,'inflation':3.5,
                   'unemployment':6.4,'debt_pct_gdp':47.7,'currency':'NIO',
                   'main_sectors':['agriculture','élevage','textile','tourisme'],
                   'sectors':sec(18,26,56)},
        'military':{'strength':2,'active_personnel':12000,'nuclear_weapons':False,
                    'defense_budget_pct':0.7,'equipment':eq(2,0.7,13.2)},
        'national_stats':ns(55,72,45,38),
        'relations':{'USA':-20,'RUS':35,'CUB':55,'VEN':55,'MEX':30,'GTM':25,'CRI':30,'HND':15},
        'personality_traits':['sandiniste','anti_américain','allié_venezuela','autoritaire'],
        'description':"Gouverné par Daniel Ortega depuis 2007, le Nicaragua s'appuie sur le Venezuela pour son pétrole subventionné et maintient des liens étroits avec Cuba et la Russie.",
        'color':'#003F87',
    },

    # ── Afrique de l'Ouest ──────────────────────────────────────────────────
    'SEN': {
        'id':'SEN','name':'Sénégal','flag':'🇸🇳','capital':'Dakar',
        'continent':'Afrique','population':15412000,
        'government_type':'présidentiel','ideology':'démocratie_libérale',
        'leader':'Macky Sall',
        'alliances':[],
        'economy':{'gdp':15.9,'gdp_per_capita':1032,'gdp_growth':6.5,'inflation':1.3,
                   'unemployment':15.7,'debt_pct_gdp':58.2,'currency':'XOF',
                   'main_sectors':['pêche','phosphates','tourisme','services','agriculture'],
                   'sectors':sec(16,24,60)},
        'military':{'strength':2,'active_personnel':17000,'nuclear_weapons':False,
                    'defense_budget_pct':1.7,'equipment':eq(2,1.7,15.9)},
        'national_stats':ns(58,58,25,32),
        'relations':{'FRA':65,'USA':50,'MAR':55,'CIV':50,'MLI':40,'GMB':35,'GIN':40,'GNB':35},
        'personality_traits':['pro_français','stable','CEDEAO','modéré'],
        'description':"L'une des démocraties les plus stables d'Afrique de l'Ouest, le Sénégal est un partenaire clé de la France et un pôle régional de stabilité face au jihadisme sahélien.",
        'color':'#00853F',
    },
    'MLI': {
        'id':'MLI','name':'Mali','flag':'🇲🇱','capital':'Bamako',
        'continent':'Afrique','population':17994000,
        'government_type':'présidentiel','ideology':'démocratie_fragile',
        'leader':'Ibrahim Boubacar Keïta',
        'alliances':[],
        'economy':{'gdp':14.3,'gdp_per_capita':794,'gdp_growth':5.3,'inflation':1.4,
                   'unemployment':8.1,'debt_pct_gdp':35.5,'currency':'XOF',
                   'main_sectors':['or','agriculture','coton','élevage'],
                   'sectors':sec(38,18,44)},
        'military':{'strength':2,'active_personnel':18000,'nuclear_weapons':False,
                    'defense_budget_pct':2.9,'equipment':eq(2,2.9,14.3)},
        'national_stats':ns(32,52,22,22),
        'relations':{'FRA':40,'USA':35,'DZA':45,'NER':40,'BFA':45,'SEN':40,'GIN':35,'MRT':40},
        'personality_traits':['instable','jihadisme_nord','présence_barkhane','dépendant_france'],
        'description':"Depuis le coup d'État de 2012 et l'intervention française Serval/Barkhane, le Mali lutte contre les groupes jihadistes dans le Sahel, son nord restant très instable.",
        'color':'#14B53A',
    },
    'BFA': {
        'id':'BFA','name':'Burkina Faso','flag':'🇧🇫','capital':'Ouagadougou',
        'continent':'Afrique','population':18450000,
        'government_type':'présidentiel','ideology':'démocratie_fragile',
        'leader':'Roch Marc Christian Kaboré',
        'alliances':[],
        'economy':{'gdp':12.3,'gdp_per_capita':668,'gdp_growth':5.9,'inflation':1.3,
                   'unemployment':7.9,'debt_pct_gdp':36.3,'currency':'XOF',
                   'main_sectors':['or','coton','élevage','agriculture'],
                   'sectors':sec(34,20,46)},
        'military':{'strength':2,'active_personnel':11200,'nuclear_weapons':False,
                    'defense_budget_pct':1.5,'equipment':eq(2,1.5,12.3)},
        'national_stats':ns(48,58,22,25),
        'relations':{'FRA':45,'MLI':45,'NER':50,'GHA':45,'CIV':50,'BEN':45,'TGO':40,'SEN':40},
        'personality_traits':['CEDEAO','sahélien','menace_jihadiste_croissante','transition_démocratique'],
        'description':"Roch Marc Christian Kaboré est élu en 2015, marquant la première alternance pacifique depuis l'indépendance. Le pays fait face à une menace jihadiste croissante aux frontières du Mali.",
        'color':'#EF2B2D',
    },
    'NER': {
        'id':'NER','name':'Niger','flag':'🇳🇪','capital':'Niamey',
        'continent':'Afrique','population':20673000,
        'government_type':'présidentiel','ideology':'démocratie_fragile',
        'leader':'Mahamadou Issoufou',
        'alliances':[],
        'economy':{'gdp':7.8,'gdp_per_capita':377,'gdp_growth':5.2,'inflation':1.4,
                   'unemployment':2.6,'debt_pct_gdp':49.6,'currency':'XOF',
                   'main_sectors':['uranium','pétrole','élevage','agriculture'],
                   'sectors':sec(40,17,43)},
        'military':{'strength':2,'active_personnel':12000,'nuclear_weapons':False,
                    'defense_budget_pct':2.0,'equipment':eq(2,2.0,7.8)},
        'national_stats':ns(42,45,28,22),
        'relations':{'FRA':50,'USA':45,'NGA':45,'MLI':40,'BFA':50,'TCD':40,'LBY':-20,'DZA':40},
        'personality_traits':['sahélien','CEDEAO','uranium_français','boko_haram','pauvreté_extrême'],
        'description':"Parmi les pays les plus pauvres du monde, le Niger est néanmoins un partenaire stratégique de l'Occident face à Boko Haram et dispose d'importantes ressources en uranium exploitées par Areva.",
        'color':'#E05206',
    },
    'TCD': {
        'id':'TCD','name':'Tchad','flag':'🇹🇩','capital':'N\'Djamena',
        'continent':'Afrique','population':14453000,
        'government_type':'présidentiel_autoritaire','ideology':'autoritaire',
        'leader':'Idriss Déby',
        'alliances':[],
        'economy':{'gdp':11.0,'gdp_per_capita':761,'gdp_growth':-6.3,'inflation':3.3,
                   'unemployment':7.4,'debt_pct_gdp':53.3,'currency':'XAF',
                   'main_sectors':['pétrole','élevage','agriculture','pêche'],
                   'sectors':sec(22,33,45)},
        'military':{'strength':3,'active_personnel':25350,'nuclear_weapons':False,
                    'defense_budget_pct':3.3,'equipment':eq(3,3.3,11.0)},
        'national_stats':ns(45,42,55,28),
        'relations':{'FRA':55,'USA':40,'NGA':40,'NER':40,'CMR':40,'SDN':-20,'LBY':-15,'CAF':30},
        'personality_traits':['autoritaire','allié_france','lutte_boko_haram','pétrole','instable'],
        'description':"Allié militaire clé de la France au Sahel, le Tchad d'Idriss Déby joue un rôle central dans la lutte contre Boko Haram et les groupes armés de la région, malgré une gouvernance autoritaire.",
        'color':'#002664',
    },
    'GIN': {
        'id':'GIN','name':'Guinée','flag':'🇬🇳','capital':'Conakry',
        'continent':'Afrique','population':12717000,
        'government_type':'présidentiel','ideology':'semi_démocratique',
        'leader':'Alpha Condé',
        'alliances':[],
        'economy':{'gdp':6.7,'gdp_per_capita':527,'gdp_growth':5.0,'inflation':8.5,
                   'unemployment':6.9,'debt_pct_gdp':57.6,'currency':'GNF',
                   'main_sectors':['bauxite','or','diamants','agriculture'],
                   'sectors':sec(20,35,45)},
        'military':{'strength':2,'active_personnel':9700,'nuclear_weapons':False,
                    'defense_budget_pct':1.6,'equipment':eq(2,1.6,6.7)},
        'national_stats':ns(45,58,28,25),
        'relations':{'FRA':40,'USA':35,'SEN':40,'MLI':40,'CIV':35,'SLE':35,'LBR':35,'GNB':40},
        'personality_traits':['ressources_minières','CEDEAO','post_ébola','autoritaire_modéré'],
        'description':"La Guinée possède les plus grandes réserves de bauxite au monde mais reste très pauvre. Alpha Condé gouverne dans un contexte de tensions ethniques post-élection.",
        'color':'#CE1126',
    },
    'SLE': {
        'id':'SLE','name':'Sierra Leone','flag':'🇸🇱','capital':'Freetown',
        'continent':'Afrique','population':7396000,
        'government_type':'présidentiel','ideology':'démocratie_fragile',
        'leader':'Ernest Bai Koroma',
        'alliances':[],
        'economy':{'gdp':4.1,'gdp_per_capita':554,'gdp_growth':-21.5,'inflation':8.2,
                   'unemployment':60.0,'debt_pct_gdp':40.8,'currency':'SLL',
                   'main_sectors':['diamants','mines','agriculture','pêche'],
                   'sectors':sec(58,10,32)},
        'military':{'strength':1,'active_personnel':8500,'nuclear_weapons':False,
                    'defense_budget_pct':0.9,'equipment':eq(1,0.9,4.1)},
        'national_stats':ns(48,58,22,22),
        'relations':{'GBR':55,'USA':40,'NGA':40,'GIN':35,'LBR':30,'SEN':35},
        'personality_traits':['post_guerre_civile','post_ébola','CEDEAO','dépendant_aide'],
        'description':"Encore en reconstruction après la guerre civile et l'épidémie d'Ebola de 2014-2016, la Sierra Leone voit son PIB s'effondrer de 21% en 2015 avec la chute des cours du minerai de fer.",
        'color':'#1EB53A',
    },
    'LBR': {
        'id':'LBR','name':'Liberia','flag':'🇱🇷','capital':'Monrovia',
        'continent':'Afrique','population':4615000,
        'government_type':'présidentiel','ideology':'démocratie_fragile',
        'leader':'Ellen Johnson Sirleaf',
        'alliances':[],
        'economy':{'gdp':2.1,'gdp_per_capita':455,'gdp_growth':0.0,'inflation':7.6,
                   'unemployment':85.0,'debt_pct_gdp':27.9,'currency':'LRD',
                   'main_sectors':['caoutchouc','minerai_fer','bois','agriculture'],
                   'sectors':sec(34,14,52)},
        'military':{'strength':1,'active_personnel':2000,'nuclear_weapons':False,
                    'defense_budget_pct':0.8,'equipment':eq(1,0.8,2.1)},
        'national_stats':ns(45,55,22,22),
        'relations':{'USA':55,'GBR':45,'NGA':40,'GIN':35,'CIV':35,'SLE':30},
        'personality_traits':['post_guerre_civile','pro_américain','CEDEAO','reconstruction'],
        'description':"Ellen Johnson Sirleaf, première femme élue chef d'État en Afrique, dirige un Liberia encore fragilisé par la guerre civile et les séquelles de l'épidémie d'Ebola.",
        'color':'#BF0A30',
    },
    'GNB': {
        'id':'GNB','name':'Guinée-Bissau','flag':'🇬🇼','capital':'Bissau',
        'continent':'Afrique','population':1844000,
        'government_type':'semi_présidentiel','ideology':'démocratie_fragile',
        'leader':'José Mário Vaz',
        'alliances':[],
        'economy':{'gdp':1.2,'gdp_per_capita':652,'gdp_growth':5.1,'inflation':1.4,
                   'unemployment':6.9,'debt_pct_gdp':53.0,'currency':'XOF',
                   'main_sectors':['noix_de_cajou','pêche','agriculture'],
                   'sectors':sec(45,12,43)},
        'military':{'strength':1,'active_personnel':4450,'nuclear_weapons':False,
                    'defense_budget_pct':1.8,'equipment':eq(1,1.8,1.2)},
        'national_stats':ns(32,58,18,18),
        'relations':{'SEN':45,'PRT':45,'GIN':40,'FRA':35,'GNB':0,'CIV':30},
        'personality_traits':['instable','narco_transit','CEDEAO','influence_portugaise'],
        'description':"La Guinée-Bissau est l'un des États les plus fragiles au monde, régulièrement secoué par des coups d'État et utilisé comme plaque tournante du trafic de cocaïne.",
        'color':'#CE1126',
    },
    'GMB': {
        'id':'GMB','name':'Gambie','flag':'🇬🇲','capital':'Banjul',
        'continent':'Afrique','population':2039000,
        'government_type':'présidentiel_autoritaire','ideology':'autoritaire',
        'leader':'Yahya Jammeh',
        'alliances':[],
        'economy':{'gdp':1.0,'gdp_per_capita':490,'gdp_growth':4.3,'inflation':6.8,
                   'unemployment':30.0,'debt_pct_gdp':88.1,'currency':'GMD',
                   'main_sectors':['tourisme','arachides','pêche'],
                   'sectors':sec(22,12,66)},
        'military':{'strength':1,'active_personnel':800,'nuclear_weapons':False,
                    'defense_budget_pct':1.4,'equipment':eq(1,1.4,1.0)},
        'national_stats':ns(35,52,18,20),
        'relations':{'SEN':-15,'GBR':20,'USA':10,'NGA':30,'GIN':30,'CIV':25},
        'personality_traits':['autoritaire','isolationniste','anti_occidental','imprévisible'],
        'description':"Yahya Jammeh dirige la Gambie d'une main de fer depuis 1994, se distinguant par des déclarations extrémistes et une rupture progressive avec les organisations régionales.",
        'color':'#3A7728',
    },
    'MRT': {
        'id':'MRT','name':'Mauritanie','flag':'🇲🇷','capital':'Nouakchott',
        'continent':'Afrique','population':4162000,
        'government_type':'présidentiel_autoritaire','ideology':'autoritaire',
        'leader':'Mohamed Ould Abdel Aziz',
        'alliances':[],
        'economy':{'gdp':5.4,'gdp_per_capita':1297,'gdp_growth':1.6,'inflation':1.5,
                   'unemployment':31.0,'debt_pct_gdp':92.0,'currency':'MRO',
                   'main_sectors':['fer','or','pêche','pétrole'],
                   'sectors':sec(20,30,50)},
        'military':{'strength':2,'active_personnel':15870,'nuclear_weapons':False,
                    'defense_budget_pct':3.3,'equipment':eq(2,3.3,5.4)},
        'national_stats':ns(50,38,52,32),
        'relations':{'FRA':45,'USA':40,'MAR':50,'SEN':45,'MLI':40,'DZA':40,'MRT':0},
        'personality_traits':['sahélien','lutte_AQMI','arabo_africain','autoritaire'],
        'description':"La Mauritanie a réussi à contenir la menace djihadiste grâce à une politique de coopération sécuritaire avec la France et les États-Unis, sous la présidence autoritaire d'Abdel Aziz.",
        'color':'#006233',
    },
    'BEN': {
        'id':'BEN','name':'Bénin','flag':'🇧🇯','capital':'Porto-Novo',
        'continent':'Afrique','population':11175000,
        'government_type':'présidentiel','ideology':'démocratie_libérale',
        'leader':'Thomas Boni Yayi',
        'alliances':[],
        'economy':{'gdp':8.9,'gdp_per_capita':796,'gdp_growth':5.2,'inflation':0.3,
                   'unemployment':1.0,'debt_pct_gdp':47.5,'currency':'XOF',
                   'main_sectors':['coton','transit_nigéria','agriculture','tourisme'],
                   'sectors':sec(24,24,52)},
        'military':{'strength':1,'active_personnel':7250,'nuclear_weapons':False,
                    'defense_budget_pct':0.9,'equipment':eq(1,0.9,8.9)},
        'national_stats':ns(52,62,22,28),
        'relations':{'NGA':55,'FRA':50,'NER':45,'BFA':45,'TGO':45,'GHA':45,'USA':40},
        'personality_traits':['stable','CEDEAO','transit_nigéria','pro_occidental'],
        'description':"Le Bénin est l'une des démocraties les plus stables d'Afrique de l'Ouest, jouant un rôle de hub commercial entre le Nigeria et les pays sahéliens enclavés.",
        'color':'#008751',
    },
    'TGO': {
        'id':'TGO','name':'Togo','flag':'🇹🇬','capital':'Lomé',
        'continent':'Afrique','population':7606000,
        'government_type':'présidentiel_autoritaire','ideology':'autoritaire',
        'leader':'Faure Gnassingbé',
        'alliances':[],
        'economy':{'gdp':4.7,'gdp_per_capita':618,'gdp_growth':5.3,'inflation':1.8,
                   'unemployment':6.9,'debt_pct_gdp':81.4,'currency':'XOF',
                   'main_sectors':['phosphates','coton','port_Lomé','commerce'],
                   'sectors':sec(28,21,51)},
        'military':{'strength':1,'active_personnel':10000,'nuclear_weapons':False,
                    'defense_budget_pct':1.9,'equipment':eq(1,1.9,4.7)},
        'national_stats':ns(42,55,22,25),
        'relations':{'FRA':50,'NGA':45,'GHA':40,'BEN':45,'BFA':40,'USA':35},
        'personality_traits':['autoritaire','CEDEAO','hub_commercial','phosphates'],
        'description':"Faure Gnassingbé dirige le Togo depuis 2005, perpétuant la dynastie familiale. Le port de Lomé est un hub régional important pour les pays enclavés du Sahel.",
        'color':'#006A4E',
    },

    # ── Afrique centrale ─────────────────────────────────────────────────────
    'COD': {
        'id':'COD','name':'République Démocratique du Congo','flag':'🇨🇩','capital':'Kinshasa',
        'continent':'Afrique','population':79722000,
        'government_type':'présidentiel','ideology':'présidentiel_autoritaire',
        'leader':'Joseph Kabila',
        'alliances':[],
        'economy':{'gdp':38.0,'gdp_per_capita':477,'gdp_growth':2.4,'inflation':2.2,
                   'unemployment':10.0,'debt_pct_gdp':21.5,'currency':'CDF',
                   'main_sectors':['coltan','cobalt','cuivre','diamants','or','bois'],
                   'sectors':sec(20,32,48)},
        'military':{'strength':3,'active_personnel':134250,'nuclear_weapons':False,
                    'defense_budget_pct':1.2,'equipment':eq(3,1.2,38.0)},
        'national_stats':ns(40,65,42,25),
        'relations':{'AGO':35,'RWA':-30,'UGA':-20,'ZMB':40,'TZA':40,'BDI':20,'CAF':30,'COG':40,'FRA':35,'USA':30},
        'personality_traits':['ressources_naturelles','conflits_est','autoritaire','géant_africain'],
        'description':"La RDC est le pays le plus riche en ressources naturelles d'Afrique mais l'un des plus pauvres. L'Est du pays reste en proie à des groupes armés malgré la présence de la MONUSCO.",
        'color':'#007FFF',
    },
    'COG': {
        'id':'COG','name':'République du Congo','flag':'🇨🇬','capital':'Brazzaville',
        'continent':'Afrique','population':5125000,
        'government_type':'présidentiel_autoritaire','ideology':'autoritaire',
        'leader':'Denis Sassou Nguesso',
        'alliances':[],
        'economy':{'gdp':8.6,'gdp_per_capita':1683,'gdp_growth':2.6,'inflation':3.2,
                   'unemployment':53.0,'debt_pct_gdp':92.0,'currency':'XAF',
                   'main_sectors':['pétrole','bois','ciment','agriculture'],
                   'sectors':sec(4,58,38)},
        'military':{'strength':2,'active_personnel':10000,'nuclear_weapons':False,
                    'defense_budget_pct':3.0,'equipment':eq(2,3.0,8.6)},
        'national_stats':ns(50,38,82,38),
        'relations':{'FRA':55,'AGO':40,'COD':30,'GAB':45,'CMR':40,'CHN':45},
        'personality_traits':['autoritaire','pétrole','allié_france','néopatrimonial'],
        'description':"Denis Sassou Nguesso, au pouvoir depuis 1997, dirige le Congo-Brazzaville avec une économie dominée par le pétrole et de forts liens avec la France et la Chine.",
        'color':'#009A00',
    },
    'CAF': {
        'id':'CAF','name':'République Centrafricaine','flag':'🇨🇫','capital':'Bangui',
        'continent':'Afrique','population':4998000,
        'government_type':'présidentiel','ideology':'démocratie_fragile',
        'leader':'Faustin-Archange Touadéra',
        'alliances':[],
        'economy':{'gdp':1.9,'gdp_per_capita':380,'gdp_growth':4.8,'inflation':4.7,
                   'unemployment':65.0,'debt_pct_gdp':56.4,'currency':'XAF',
                   'main_sectors':['diamants','bois','or','agriculture'],
                   'sectors':sec(42,14,44)},
        'military':{'strength':1,'active_personnel':7150,'nuclear_weapons':False,
                    'defense_budget_pct':1.3,'equipment':eq(1,1.3,1.9)},
        'national_stats':ns(22,48,15,15),
        'relations':{'FRA':35,'CMR':30,'TCD':25,'COD':25,'COG':25,'SDN':-20,'USA':25},
        'personality_traits':['état_faillit','MINUSCA','conflit_armé','Seleka_Anti-Balaka'],
        'description':"La RCA est l'un des États les plus fragiles du monde, déchiré par les milices Séléka et Anti-Balaka depuis 2013, sous intervention de l'ONU (MINUSCA) et de la France (Sangaris).",
        'color':'#289728',
    },
    'GAB': {
        'id':'GAB','name':'Gabon','flag':'🇬🇦','capital':'Libreville',
        'continent':'Afrique','population':1979000,
        'government_type':'présidentiel_autoritaire','ideology':'autoritaire',
        'leader':'Ali Bongo Ondimba',
        'alliances':[],
        'economy':{'gdp':14.5,'gdp_per_capita':7330,'gdp_growth':3.9,'inflation':2.1,
                   'unemployment':20.4,'debt_pct_gdp':64.2,'currency':'XAF',
                   'main_sectors':['pétrole','manganèse','bois','agriculture'],
                   'sectors':sec(4,54,42)},
        'military':{'strength':2,'active_personnel':4700,'nuclear_weapons':False,
                    'defense_budget_pct':1.4,'equipment':eq(2,1.4,14.5)},
        'national_stats':ns(55,32,88,42),
        'relations':{'FRA':60,'CMR':45,'COG':45,'CHN':40,'USA':40,'AGO':35},
        'personality_traits':['pétrole','allié_france','stable','autoritaire_modéré'],
        'description':"Le Gabon est un pays pétrolier relativement prospère mais inégalitaire, gouverné par Ali Bongo dans la continuité de son père, étroit allié de Paris.",
        'color':'#009E60',
    },
    'GNQ': {
        'id':'GNQ','name':'Guinée Équatoriale','flag':'🇬🇶','capital':'Malabo',
        'continent':'Afrique','population':845000,
        'government_type':'présidentiel_autoritaire','ideology':'dictature',
        'leader':'Teodoro Obiang Nguema',
        'alliances':[],
        'economy':{'gdp':12.2,'gdp_per_capita':14440,'gdp_growth':-9.6,'inflation':2.6,
                   'unemployment':8.6,'debt_pct_gdp':23.0,'currency':'XAF',
                   'main_sectors':['pétrole','gaz','construction','bois'],
                   'sectors':sec(1,73,26)},
        'military':{'strength':2,'active_personnel':1450,'nuclear_weapons':False,
                    'defense_budget_pct':1.6,'equipment':eq(2,1.6,12.2)},
        'national_stats':ns(45,18,95,42),
        'relations':{'ESP':40,'USA':40,'CHN':45,'CMR':35,'GAB':40,'NGA':35,'FRA':35},
        'personality_traits':['dictature_pétrolière','corruption_extrême','ESP_lien','isolé'],
        'description':"Obiang gouverne depuis 1979 dans une dictature pétrolière parmi les plus corrompues du monde, malgré un PIB par habitant élevé dû aux revenus pétroliers.",
        'color':'#3E9A00',
    },

    # ── Afrique de l'Est ──────────────────────────────────────────────────────
    'UGA': {
        'id':'UGA','name':'Ouganda','flag':'🇺🇬','capital':'Kampala',
        'continent':'Afrique','population':41488000,
        'government_type':'présidentiel_autoritaire','ideology':'autoritaire',
        'leader':'Yoweri Museveni',
        'alliances':[],
        'economy':{'gdp':23.0,'gdp_per_capita':555,'gdp_growth':4.8,'inflation':6.6,
                   'unemployment':9.4,'debt_pct_gdp':38.5,'currency':'UGX',
                   'main_sectors':['café','poisson','fleurs','thé','or'],
                   'sectors':sec(24,25,51)},
        'military':{'strength':3,'active_personnel':45000,'nuclear_weapons':False,
                    'defense_budget_pct':1.5,'equipment':eq(3,1.5,23.0)},
        'national_stats':ns(52,72,35,28),
        'relations':{'KEN':50,'TZA':45,'RWA':35,'COD':-15,'SDN':25,'USA':40,'GBR':45},
        'personality_traits':['autoritaire','stabilité_régionale','anti_LRA','influence_régionale'],
        'description':"Museveni dirige l'Ouganda depuis 1986, maintenant une stabilité relative dans une région tumultueuse et jouant un rôle actif dans les crises en RDC et au Soudan du Sud.",
        'color':'#FCDC04',
    },
    'RWA': {
        'id':'RWA','name':'Rwanda','flag':'🇷🇼','capital':'Kigali',
        'continent':'Afrique','population':12208000,
        'government_type':'présidentiel_autoritaire','ideology':'autoritaire',
        'leader':'Paul Kagame',
        'alliances':[],
        'economy':{'gdp':8.9,'gdp_per_capita':730,'gdp_growth':6.0,'inflation':5.7,
                   'unemployment':2.7,'debt_pct_gdp':37.8,'currency':'RWF',
                   'main_sectors':['thé','café','tourisme','services','minéraux'],
                   'sectors':sec(30,17,53)},
        'military':{'strength':3,'active_personnel':33000,'nuclear_weapons':False,
                    'defense_budget_pct':1.2,'equipment':eq(3,1.2,8.9)},
        'national_stats':ns(60,72,28,32),
        'relations':{'UGA':35,'TZA':50,'KEN':50,'COD':-35,'BDI':-20,'USA':45,'GBR':50},
        'personality_traits':['post_génocide','développement_rapide','autoritaire_kagame','influence_est'],
        'description':"Sous Paul Kagame, le Rwanda connaît une croissance économique remarquable et une reconstruction post-génocide impressionnante, mais au prix d'un régime très contrôlé des libertés.",
        'color':'#20603D',
    },
    'BDI': {
        'id':'BDI','name':'Burundi','flag':'🇧🇮','capital':'Bujumbura',
        'continent':'Afrique','population':10872000,
        'government_type':'présidentiel_autoritaire','ideology':'autoritaire',
        'leader':'Pierre Nkurunziza',
        'alliances':[],
        'economy':{'gdp':3.2,'gdp_per_capita':295,'gdp_growth':-3.9,'inflation':5.6,
                   'unemployment':14.0,'debt_pct_gdp':46.1,'currency':'BIF',
                   'main_sectors':['café','thé','sucre','coton'],
                   'sectors':sec(38,16,46)},
        'military':{'strength':2,'active_personnel':20000,'nuclear_weapons':False,
                    'defense_budget_pct':2.4,'equipment':eq(2,2.4,3.2)},
        'national_stats':ns(35,55,18,18),
        'relations':{'RWA':-25,'TZA':35,'COD':20,'UGA':25,'FRA':25,'USA':20},
        'personality_traits':['crise_politique','troisième_mandat','répression','pauvreté_extrême'],
        'description':"Le Burundi est plongé dans une grave crise depuis 2015, quand Pierre Nkurunziza a briguéun troisième mandat inconstitutionnel, provoquant violences et exodes massifs.",
        'color':'#CE1126',
    },
    'SSD': {
        'id':'SSD','name':'Soudan du Sud','flag':'🇸🇸','capital':'Djouba',
        'continent':'Afrique','population':12575000,
        'government_type':'présidentiel','ideology':'démocratie_fragile',
        'leader':'Salva Kiir',
        'alliances':[],
        'economy':{'gdp':12.5,'gdp_per_capita':994,'gdp_growth':-5.5,'inflation':52.8,
                   'unemployment':20.0,'debt_pct_gdp':60.8,'currency':'SSP',
                   'main_sectors':['pétrole','agriculture','élevage'],
                   'sectors':sec(8,56,36)},
        'military':{'strength':3,'active_personnel':185000,'nuclear_weapons':False,
                    'defense_budget_pct':12.4,'equipment':eq(3,12.4,12.5)},
        'national_stats':ns(22,38,45,18),
        'relations':{'SDN':-40,'ETH':30,'UGA':35,'KEN':35,'USA':35,'CHN':40},
        'personality_traits':['guerre_civile','Kiir_Machar','pétrole','état_faillit'],
        'description':"Indépendant depuis 2011, le Soudan du Sud est ravagé par une guerre civile entre les forces de Salva Kiir et celles de Riek Machar depuis 2013, causant une catastrophe humanitaire.",
        'color':'#078930',
    },
    'ERI': {
        'id':'ERI','name':'Érythrée','flag':'🇪🇷','capital':'Asmara',
        'continent':'Afrique','population':5228000,
        'government_type':'présidentiel_autoritaire','ideology':'dictature',
        'leader':'Isaias Afwerki',
        'alliances':[],
        'economy':{'gdp':5.4,'gdp_per_capita':1033,'gdp_growth':3.5,'inflation':12.3,
                   'unemployment':12.0,'debt_pct_gdp':125.8,'currency':'ERN',
                   'main_sectors':['mines','agriculture','élevage','pêche'],
                   'sectors':sec(11,29,60)},
        'military':{'strength':3,'active_personnel':300000,'nuclear_weapons':False,
                    'defense_budget_pct':10.0,'equipment':eq(3,10.0,5.4)},
        'national_stats':ns(42,35,28,22),
        'relations':{'ETH':-80,'DJI':-30,'SDN':25,'EGY':30,'CHN':30,'USA':-20},
        'personality_traits':['dictature','isolé','service_national_illimité','anti_éthiopie'],
        'description':"L'Érythrée d'Isaias Afwerki est l'un des pays les plus fermés au monde, soumis à un service national quasi illimité et en état de guerre froide permanent avec l'Éthiopie.",
        'color':'#4189DD',
    },
    'DJI': {
        'id':'DJI','name':'Djibouti','flag':'🇩🇯','capital':'Djibouti',
        'continent':'Afrique','population':942000,
        'government_type':'présidentiel_autoritaire','ideology':'autoritaire',
        'leader':'Ismail Omar Guelleh',
        'alliances':[],
        'economy':{'gdp':1.9,'gdp_per_capita':2015,'gdp_growth':6.5,'inflation':2.7,
                   'unemployment':60.0,'debt_pct_gdp':79.2,'currency':'DJF',
                   'main_sectors':['port','bases_militaires_étrangères','services','transit'],
                   'sectors':sec(3,17,80)},
        'military':{'strength':1,'active_personnel':8000,'nuclear_weapons':False,
                    'defense_budget_pct':3.5,'equipment':eq(1,3.5,1.9)},
        'national_stats':ns(45,12,18,28),
        'relations':{'FRA':65,'USA':60,'CHN':50,'ETH':55,'SOM':30,'ERI':-30,'ARE':45},
        'personality_traits':['bases_militaires_étrangères','hub_logistique','autoritaire','stratégique'],
        'description':"Djibouti héberge des bases militaires françaises, américaines, japonaises et chinoises, tirant parti de sa position stratégique sur le détroit de Bab-el-Mandeb.",
        'color':'#6AB2E7',
    },

    # ── Afrique australe ─────────────────────────────────────────────────────
    'MOZ': {
        'id':'MOZ','name':'Mozambique','flag':'🇲🇿','capital':'Maputo',
        'continent':'Afrique','population':28829000,
        'government_type':'présidentiel','ideology':'démocratie_fragile',
        'leader':'Filipe Nyusi',
        'alliances':[],
        'economy':{'gdp':14.9,'gdp_per_capita':517,'gdp_growth':3.6,'inflation':19.9,
                   'unemployment':25.0,'debt_pct_gdp':113.8,'currency':'MZN',
                   'main_sectors':['gaz_naturel','aluminium','charbon','agriculture'],
                   'sectors':sec(25,20,55)},
        'military':{'strength':2,'active_personnel':11200,'nuclear_weapons':False,
                    'defense_budget_pct':0.9,'equipment':eq(2,0.9,14.9)},
        'national_stats':ns(50,55,35,28),
        'relations':{'ZAF':60,'TZA':50,'ZMB':45,'PRT':50,'CHN':45,'USA':40,'BRA':40},
        'personality_traits':['SADC','post_guerre_civile','gaz_naturel_Rovuma','pauvreté'],
        'description':"Le Mozambique fait face à une grave crise de la dette cachée découverte en 2016 (tuna bonds), mais ses réserves de gaz naturel dans le bassin du Rovuma suscitent les convoitises.",
        'color':'#009A44',
    },
    'MDG': {
        'id':'MDG','name':'Madagascar','flag':'🇲🇬','capital':'Antananarivo',
        'continent':'Afrique','population':24894000,
        'government_type':'présidentiel','ideology':'démocratie_fragile',
        'leader':'Hery Rajaonarimampianina',
        'alliances':[],
        'economy':{'gdp':10.1,'gdp_per_capita':406,'gdp_growth':4.1,'inflation':7.4,
                   'unemployment':21.0,'debt_pct_gdp':38.4,'currency':'MGA',
                   'main_sectors':['vanille','graphite','tourisme','agriculture','chrome'],
                   'sectors':sec(26,17,57)},
        'military':{'strength':1,'active_personnel':13500,'nuclear_weapons':False,
                    'defense_budget_pct':0.7,'equipment':eq(1,0.7,10.1)},
        'national_stats':ns(45,68,28,25),
        'relations':{'FRA':55,'MUS':40,'ZAF':45,'CHN':40,'IND':35,'USA':35},
        'personality_traits':['instable','île','biodiversité','SADC','économie_fragile'],
        'description':"Madagascar, après la crise politique de 2009-2013, tente de stabiliser son économie sous Rajaonarimampianina, restant très dépendant de l'aide internationale.",
        'color':'#FC3D32',
    },
    'MWI': {
        'id':'MWI','name':'Malawi','flag':'🇲🇼','capital':'Lilongwe',
        'continent':'Afrique','population':18622000,
        'government_type':'présidentiel','ideology':'démocratie_libérale',
        'leader':'Peter Mutharika',
        'alliances':[],
        'economy':{'gdp':6.3,'gdp_per_capita':338,'gdp_growth':2.5,'inflation':21.9,
                   'unemployment':17.3,'debt_pct_gdp':59.4,'currency':'MWK',
                   'main_sectors':['tabac','thé','sucre','café','coton'],
                   'sectors':sec(28,15,57)},
        'military':{'strength':1,'active_personnel':5300,'nuclear_weapons':False,
                    'defense_budget_pct':0.9,'equipment':eq(1,0.9,6.3)},
        'national_stats':ns(48,62,18,22),
        'relations':{'MOZ':45,'TZA':50,'ZMB':50,'ZAF':55,'GBR':50,'USA':45},
        'personality_traits':['SADC','enclavé','dépendant_aide','tabac','pauvre'],
        'description':"Le Malawi est l'un des pays les plus pauvres au monde, très dépendant de l'aide étrangère et du tabac, enclavé entre le Mozambique, la Tanzanie et la Zambie.",
        'color':'#000000',
    },
    'NAM': {
        'id':'NAM','name':'Namibie','flag':'🇳🇦','capital':'Windhoek',
        'continent':'Afrique','population':2480000,
        'government_type':'présidentiel','ideology':'démocratie_libérale',
        'leader':'Hage Geingob',
        'alliances':[],
        'economy':{'gdp':11.5,'gdp_per_capita':4640,'gdp_growth':4.7,'inflation':6.7,
                   'unemployment':28.1,'debt_pct_gdp':40.1,'currency':'NAD',
                   'main_sectors':['diamants','uranium','or','zinc','pêche'],
                   'sectors':sec(5,28,67)},
        'military':{'strength':2,'active_personnel':9200,'nuclear_weapons':False,
                    'defense_budget_pct':3.4,'equipment':eq(2,3.4,11.5)},
        'national_stats':ns(62,42,35,42),
        'relations':{'ZAF':65,'AGO':50,'BWA':55,'ZMB':50,'USA':45,'DEU':50,'GBR':45},
        'personality_traits':['SADC','ressources_minières','stable','inégalités_fortes'],
        'description':"La Namibie est l'une des démocraties les plus stables d'Afrique australe, riche en ressources naturelles mais confrontée aux inégalités héritées de l'apartheid.",
        'color':'#003580',
    },
    'BWA': {
        'id':'BWA','name':'Botswana','flag':'🇧🇼','capital':'Gaborone',
        'continent':'Afrique','population':2291000,
        'government_type':'présidentiel','ideology':'démocratie_libérale',
        'leader':'Ian Khama',
        'alliances':[],
        'economy':{'gdp':15.6,'gdp_per_capita':6810,'gdp_growth':-1.7,'inflation':3.1,
                   'unemployment':17.7,'debt_pct_gdp':19.3,'currency':'BWP',
                   'main_sectors':['diamants','tourisme','bétail','nickel'],
                   'sectors':sec(2,32,66)},
        'military':{'strength':2,'active_personnel':9000,'nuclear_weapons':False,
                    'defense_budget_pct':2.8,'equipment':eq(2,2.8,15.6)},
        'national_stats':ns(68,52,42,52),
        'relations':{'ZAF':65,'ZMB':55,'NAM':55,'ZWE':40,'USA':55,'GBR':55},
        'personality_traits':['démocratie_modèle','diamants','SADC','pro_occidental','bonne_gouvernance'],
        'description':"Le Botswana est souvent cité comme modèle de gouvernance en Afrique, transformant ses revenus diamantifères en développement humain, malgré une forte dépendance économique vis-à-vis de l'Afrique du Sud.",
        'color':'#75AADB',
    },
    'LSO': {
        'id':'LSO','name':'Lesotho','flag':'🇱🇸','capital':'Maseru',
        'continent':'Afrique','population':2204000,
        'government_type':'monarchie_constitutionnelle','ideology':'démocratie_fragile',
        'leader':'Pakalitha Mosisili',
        'alliances':[],
        'economy':{'gdp':2.9,'gdp_per_capita':1317,'gdp_growth':2.1,'inflation':5.2,
                   'unemployment':28.1,'debt_pct_gdp':35.8,'currency':'LSL',
                   'main_sectors':['textiles','eau','diamants','agriculture'],
                   'sectors':sec(6,39,55)},
        'military':{'strength':1,'active_personnel':2000,'nuclear_weapons':False,
                    'defense_budget_pct':1.9,'equipment':eq(1,1.9,2.9)},
        'national_stats':ns(38,52,25,25),
        'relations':{'ZAF':55,'MOZ':40,'GBR':40,'USA':40},
        'personality_traits':['enclavé_afrique_du_sud','eau','textile','SADC'],
        'description':"Enclave totalement entourée par l'Afrique du Sud dont il est économiquement dépendant, le Lesotho exporte son eau et ses travailleurs vers son grand voisin.",
        'color':'#009543',
    },
    'SWZ': {
        'id':'SWZ','name':'Eswatini','flag':'🇸🇿','capital':'Mbabane',
        'continent':'Afrique','population':1286000,
        'government_type':'monarchie_absolue','ideology':'autoritaire',
        'leader':'Roi Mswati III',
        'alliances':[],
        'economy':{'gdp':4.0,'gdp_per_capita':3107,'gdp_growth':1.4,'inflation':7.8,
                   'unemployment':28.0,'debt_pct_gdp':17.0,'currency':'SZL',
                   'main_sectors':['sucre','textiles','bois','tourisme'],
                   'sectors':sec(7,47,46)},
        'military':{'strength':1,'active_personnel':3000,'nuclear_weapons':False,
                    'defense_budget_pct':1.8,'equipment':eq(1,1.8,4.0)},
        'national_stats':ns(50,55,22,35),
        'relations':{'ZAF':55,'MOZ':40,'GBR':40,'USA':35},
        'personality_traits':['monarchie_absolue','SADC','enclavé','dépendant_afrique_du_sud'],
        'description':"Dernière monarchie absolue d'Afrique subsaharienne, l'Eswatini (ex-Swaziland) est gouvernée par Mswati III et dépend fortement de l'Afrique du Sud.",
        'color':'#3E5EB9',
    },
}

with open(SCENARIO_PATH, encoding='utf-8') as f:
    data = json.load(f)

for cid, country in NEW.items():
    data['countries'][cid] = country

with open(SCENARIO_PATH, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Added: {', '.join(NEW.keys())}")
print(f"Total countries: {len(data['countries'])}")
